name = "nkey-cf"
compatibility_date = "2024-01-01"
pages_build_output_dir = "out"

# KV 바인딩 (Cloudflare Pages용)
kv_namespaces = [
  {
    binding = "KEYWORDS_KV"
    id = "3b91498eb19f49b6a7355aab2c6cabf8"
    preview_id = "3b91498eb19f49b6a7355aab2c6cabf8"
  }
]

[env.production]
vars = { ENVIRONMENT = "production" }
