name = "nkey-workers"
main = "dist/worker.mjs"
compatibility_date = "2025-01-21"

# Pages: Next on Pages 산출물 배포
[build]
command = "npm run build"

[site]
bucket = ".vercel/output/static"

# --- Bindings ---
[[d1_databases]]
binding = "DB"
database_name = "NKEY_DB"
database_id = "REPLACE_WITH_D1_DB_ID"

[[r2_buckets]]
binding = "R2"
bucket_name = "nkey-r2"

[[kv_namespaces]]
binding = "KV_CACHE"
id = "REPLACE_WITH_KV_CACHE_ID"

[[kv_namespaces]]
binding = "KV_RL"
id = "REPLACE_WITH_KV_RL_ID"

[[kv_namespaces]]
binding = "KV_JOBS"
id = "REPLACE_WITH_KV_JOBS_ID"

[vars]
SITE_URL = "https://nkey-cf.pages.dev"

[env.production.vars]
# 빈값은 CF 대시보드에서 Secret으로 주입
# POSTS_API_KEY, REVALIDATE_SECRET, SLACK_WEBHOOK_URL
# MAKE_WEBHOOK_URL (선택)

# --- Cron (매 정시) ---
[triggers]
crons = ["0 * * * *"]
